spotify/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :searches, only: [:new, :create]
end

spotify/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

spotify/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

spotify/app/controllers/searches_controller.rb
class SearchesController < ApplicationController
	def new 
	end

	def create
	end
end

spotify/app/helpers/application_helper.rb
module ApplicationHelper
end

spotify/app/helpers/searches_helper.rb
module SearchesHelper
end

spotify/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spotify</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

spotify/app/views/searches/new.html.erb
<center>
<%= form_tag searches_path do %>
	<%= label_tag 'Search for your favorite artist' %><br>
	<%= text_field_tag 'artist'%>
	<%= submit_tag 'Search', {:id => 'btn-submit'} %>
<%end%>
</center>
<div class="container-fluid"->
	<div class="row">
		<div class="col-lg-4 listArtist">
			<div id="result"></div>
		</div>
		<div class="col-lg-4 listAlbum">
			<div id="album"></div>
		</div>
		<div class="col-lg-4"></div>
	</div>
</div>